### ISSUE TITLE
A benchmark between lua-resty--ffi plugin and MOSN go plugin on Envoy

### ISSUE THREAD

**Issue by Hectorsong** [kingluo/lua-resty-ffi#3]
Hi, have you ever done a  benchmark test between lua-resty--ffi go plugin and MOSN go plugin on Envoy, and I don't know which extension method to choose.

**Comment by kingluo** [comment]
@Hectorsong Yes, maybe my post is helpful for you:
http://luajit.io/posts/envoy-async-http-filter-lua-resty-ffi-vs-golang/

lua-resty-ffi has almost the same performance as go filters. In that article, I only provided the simplest demonstration. If you have further questions about the details, you are welcome to share them here, thank you!

**Comment by Hectorsong** [comment]
Appreciate it.
